# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62879e0bd1eb5e56171df88029fefdc5106496745cefd7eadffe55fce76da5f88fcd20494971ea4b52fe3ee8bc48d4183ed2140f876a90fd0295a9961a56999

test:
  secret_key_base: e3aed5c1aecf8a92d7499384395dde8ef56567d6c7350779bffb6d73876b8ac477ca28eb018eaa191b634acdb89c4c7d17728dced4887c0b6913c18d4bda10c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
